### PR TITLE
Resize sticky element on window resize event and handle responsive breakpoint

### PR DESCRIPTION
**Pull request by anthony-mangano-argus**

### CODE REVIEW

**Comment by simonihmig** [comment]
First of all, thanks for your effort! Your PR description is a bit sparse here ;) Can you please elaborate what the proposed feature(s) are, and why?

It seems there are two separate features here, so should rather be two separate PRs. The first (resizing the sticky element) seems very valuable.

But for the second (breakpoint) I am not so sure... what exactly is the use case? And why does this need to be implemented within this component? Given there is the `enabled` property to turn stickyness on and off, I would think this could better implemented outside of this component, to keep the scope of it small and focused. A wrapping component could implement the breakpoint logic and pass `enabled` accordingly down to `sticky-element`.

In any case I would ask that any new or changed functionality has to be covered by tests!

**Comment by anthony-mangano-argus** [comment]
I've made a new branch, with the window resize event handler only: "https://github.com/anthony-mangano-argus/ember-sticky-element/tree/window-resize-event-handle".
I've some difficulties to add an acceptance test for this feature. Because we can't change the size of the window in tests to check if the sticky element width was updated.

I agree with you for the second feature. I will use this addon: "https://github.com/freshbooks/ember-responsive/" with a conditionnal helper and the enable option.

**Comment by simonihmig** [comment]
> I've made a new branch, with the window resize event handler only

Cool, thanks! Can you create another PR with that? Or update this branch?

> I've some difficulties to add an acceptance test for this feature. Because we can't change the size of the window in tests to check if the sticky element width was updated.

One possible approach that could work I think: in the test we change the width of the container div (like `<div style={{containerStyle}}>{{#sticky-element}}...` and setting `this.set('containerStyle', 300px);`) and call `triggerEvent(window, 'resize')` afterwards, to simulate a resize with a relayout of the DOM...

I you can try that, that would be awesome! Otherwise create the PR as is.

**Comment by anthony-mangano-argus** [comment]
I've create an other PR with tested resize feature: 
https://github.com/kaliber5/ember-sticky-element/pull/46

Thank you for your advice.

**Pull request closed without merging**
